buildscript {
    repositories {
        mavenCentral()
        maven {
            url = "https://releases.jfrog.io/artifactory/oss-releases"
        }
    }
    dependencies {
        classpath(group: 'org.jfrog.buildinfo', name: 'build-info-extractor-gradle', version: '6.0.4')
    }
}

plugins {
    id("net.researchgate.release") version "3.1.0"
}

release {
    git {
        requireBranch.set('master')
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            url = "https://releases.jfrog.io/artifactory/oss-releases"
        }
    }


    apply plugin: 'maven-publish'
    apply plugin: 'com.jfrog.artifactory'

    group = 'org.jboss.pnc.artifactory-client'
    status = version.endsWith('-SNAPSHOT') ? 'integration' : 'release'
}

artifactoryPublish.skip = true

artifactory {
    publish {
        defaults {
            publications 'main'
        }
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'signing'

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    // Force secure versions to fix vulnerabilities
    configurations.all {
        resolutionStrategy {
            // Latest secure versions
            force 'commons-io:commons-io:2.22.0'
            force 'net.minidev:json-smart:2.6.0'
            force 'com.jayway.jsonpath:json-path:3.0.0'
            force 'com.google.guava:guava:33.4.0-jre'
            force 'org.xmlunit:xmlunit-core:2.10.0'
        }

        // Exclude problematic dependencies
        exclude group: 'commons-fileupload', module: 'commons-fileupload'
    }

    dependencies {
        implementation('org.apache.httpcomponents:httpclient:4.5.14') {
            exclude group: 'commons-codec', module: 'commons-codec'
        }
        implementation 'commons-codec:commons-codec:1.13'
        implementation 'org.apache.commons:commons-lang3:3.20.0'
        implementation 'com.fasterxml.jackson.core:jackson-core:2.22.2'
        implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.2'
        implementation 'com.fasterxml.jackson.core:jackson-annotations:2.22'
        api 'org.jfrog.filespecs:file-specs-java:1.1.2'
        api 'org.jfrog.buildinfo:build-info-api:2.43.9'
    }

    tasks.register('sourcesJar', Jar) {
        dependsOn classes
        archiveClassifier.set('sources')
        from sourceSets.main.allSource
    }

    javadoc {
        options.addStringOption('Xdoclint:none', '-quiet')
    }

    tasks.register('javadocJar', Jar) {
        dependsOn javadoc
        archiveClassifier.set('javadoc')
        from javadoc.destinationDir
    }

    test {
        useTestNG()
        testLogging {
            exceptionFormat = "full"
            events "started", "passed", "skipped", "failed", "standardOut", "standardError"
            minGranularity = 0
        }
        ignoreFailures = System.getenv("IGNORE_FAILURES") ? System.getenv("IGNORE_FAILURES").toBoolean() : false
    }

    publishing {
        publications {
            main(MavenPublication) {
                from components.java
                artifact sourcesJar
                artifact javadocJar

                pom.withXml {
                    asNode().with {
                        appendNode('packaging', 'jar')
                        appendNode('name', 'artifactory-java-client')
                        appendNode('description', 'Java client for working with Artifactory')
                        appendNode('url', 'https://github.com/jfrog/artifactory-client-java')
                        appendNode('licenses').with {
                            appendNode('license').with {
                                appendNode('name', 'The Apache Software License, Version 2.0')
                                appendNode('url', 'https://www.apache.org/licenses/LICENSE-2.0')
                            }
                        }
                        appendNode('developers').with {
                            appendNode('developer').with {
                                appendNode('name', 'JFrog')
                                appendNode('email', 'eco-system@jfrog.com')
                            }
                        }
                        appendNode('scm').with {
                            appendNode('connection', 'scm:git:git://github.com/jfrog/artifactory-client-java.git')
                            appendNode('developerConnection', 'scm:git:git@github.com:jfrog/artifactory-client-java.git')
                            appendNode('url', 'https://github.com/jfrog/artifactory-client-java')
                        }
                    }
                }
            }
        }
    }

    signing {
        def signingKey = System.getenv("GPG_SIGNING_KEY")
        def signingPassword = System.getenv("GPG_SIGNING_PASSWORD")
        if (signingKey) {
            useInMemoryPgpKeys(signingKey, signingPassword)
        } else {
            useGpgCmd()
        }
        sign publishing.publications.main
    }

    tasks.withType(Sign) {
        onlyIf { !project.version.toString().endsWith('-SNAPSHOT') }
    }
}

tasks.named("afterReleaseBuild") {
    dependsOn("publishAggregationToCentralPortal")
}
