name: Release to Maven Central

permissions: {}

on:
  workflow_dispatch:
    inputs:
      ref_to_release:
        description: 'Branch or commit to release. Default: repo default branch'
        required: false
        type: string
        default: ''
      release_type:
        description: 'Semver component to bump: major, minor or patch. Default: micro'
        required: false
        type: string
        default: 'micro'

jobs:
  call-release-job:
    permissions:
      contents: write # needed to push commit and tag back to the repository
    uses: project-ncl/shared-github-actions/.github/workflows/gradle-release.yml@118427846d0593b9fa61c254e2ae13f38f857cec
    with:
      java_version: "17"
      ref_to_release: ${{ inputs.ref_to_release }}
      release_type: ${{ inputs.release_type }}
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
