name: Java CI with Gradle

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build-gradle:
    if: github.repository == 'project-ncl/artifactory-client-java'
    uses: project-ncl/shared-github-actions/.github/workflows/gradle-ci.yml@a27e6fba6b28bbb96881ec096e9c8ea5a538f481 # v0.0.22
    with:
      java_version: "17"
      build_args: "--no-daemon --stacktrace clean build "
      upload_artifacts: true
