name: Java CI with Gradle

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build-gradle:
    if: github.repository == 'project-ncl/artifactory-client-java'
    uses: project-ncl/shared-github-actions/.github/workflows/gradle-ci.yml@646d9b629925d6405fb06ed1476aefd6b2cdca86 # v0.0.23
    with:
      java_version: "17"
      build_args: "--no-daemon --stacktrace clean build "
      upload_artifacts: true
