name: Validate GitHub Actions Workflows for this shared actions repo
permissions: {}

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:

  validate:
    uses: project-ncl/shared-github-actions/.github/workflows/validate-gh-action.yml@70502d0c707f7d7abb41b02af80fb094a022a760 # main

